### ISSUE TITLE
Discussion on our editor

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-gui#3]
As an editorial user, I want to select a series, then a book in the series, then a content file in the book, and edit it, so that I can easily make changes to the right files quickly.

**Comment by arthurattwell** [comment]
It's becoming increasingly clear – in my work with clients and team members – that the quality of our editor is a critical component of the GUI, especially for complex books like CORE. A use case from CORE is a contributor who is not part of the central client team, and so does not have access to training or support in markdown. While they aren't creating content from scratch, they might be making heavy changes, such as pasting translations over an English original.

We've tracked a whole bunch of editors in the general workflow discussion [here](https://github.com/electricbookworks/electric-book-workflow/issues/43). In building an editor into our GUI, I reckon our best tools/libraries to choose from are probably:

- [Codemirror](https://codemirror.net/doc/manual.html#styling) (not Prosemirror, which I think is too WYSIWYGy for kramdown)
- [Draft.js](http://facebook.github.io/draft-js/)
- [Substance](http://substance.io/)

They seem fully FOSS, well supported and/or mature, and extensible.

In using and extending one, our priorities are

1. Great syntax highlighting that handles kramdown (esp attributes) and Liquid tags. 
2. Validation for YAML (both in markdown page frontmatter and dedicated `.yml` files)
3. Built-in markdown cheat-sheets and dropdown-and-select tools for inserting complex structures like our Liquid `figure` include.

I still believe that editing the markdown directly is usually important. However, I'm starting to appreciate the argument for an editor that provides an abstraction from the markdown; a more constrained editing environment much like a basic HTML editor, which then writes markdown to the file. 

cc @SteveBarnett @craigmj

**Comment by SteveBarnett** [comment]
Here are some scrappy notes I made while reviewing the three above, plus some extra brain-wandering.

---

# EB GUI content notes

What are our goals for this thing?
The functionality and how much work we need to do to get it up and running.

Need listing?
But that will scare the non-techies because they show up as warnings and errors.

## Codemirror

- seems very flexible and extendable
- bunches of add-ons
- Example of highlighting mustaches. But hand-rolled, not a plugin / add-on. There are examples of people doing Liquid stuff. Don’t immediately see kramdown stuff.
- Seems very promising. Will need a fair amount of more-friendly styling.
- Seems like Codemirror can plug into things, like TInyMCE. People use it for highlighting.
- panel is their thing that might work for toolbar?

## Draft.js

- Still young: v0.10.0
- **Lots** of open issues: 288.
- We’ll have to add all the kramdown and liquid support ourselves?
- Not a front-end add-on. We’ll need a grown-up.
- Very flexible
- React, which means ES6, which means Bable.

## Substance

- Snazzy! Looks like it has a bunch of extra features (via Texture?) that we might like.
- Substance Composer desktop application might be good for ideas.
- no out of the box markdown support?
- Familiar node-based stuff
- “Substance documents” are their own thing that they convert to and from? [Convertor](https://github.com/substance/converter/) seems to have been rolled in to main substance.
- “Most importantly Substance will be a main building block of PubSweet, the decoupled full-featured content production system initiated by our friends at Coko.” from [Build your own editor with Substance](https://medium.com/@_mql/build-your-own-editor-with-substance-7790eb600109#.1ppqe1b5l)

## Jekyll-admin

- Looks nice
- No Kramdown support in Preview, it seems? Inline attribute lists don’t work.
- No support for Includes
- Definitely feels a bit 0.x.x-y.
- I guess we technically could work on that project?

## Prose.io

- What does it look like?
- Does it do `include` previews? Says yes on the box.
- How do you add includes? Is it extensible for us?

---

## Thoughts

- Thinking Jekyll CMS-y things might be a better match because they’re already with the kramdown and Liquid?
- Are we just making the glue, combining all these decoupled bits?
- Lots are paid, not FOSS
- Not a lot have kramdown support
- Is Preview useful w/o Liquid / Jekyll? Figures are big, messy, get in the way.
- [Kickster](http://kickster.nielsenramon.com/) for Jekyll + Plugin GH Pages deploys? [Automated deployment with Circle CI](https://github.com/nielsenramon/kickster#automated-deployment-with-circle-ci). But maybe less-automatic deploys with git hooks?
    - [Deploy script](https://github.com/nielsenramon/kickster/blob/master/template/bin/deploy) deletes `_site` and force pushes to gh-pages?
    - We could have a similar script? But without the force.

**Comment by SteveBarnett** [comment]
Bug: you can't delete files in the UI. It seems like this might be because Save is the action that commits, and you can't delete-then-save.

**Comment by arthurattwell** [comment]
@SteveBarnett @craigmj The original intention of this issue was simply to 'be able to edit content'. We can now do this, so that original box is ticked. That said, most of what we've noted in this thread is useful, broader thinking on the nature and quality of the editor. So I'm renaming the issue, and labelling it as an ongoing discussion, to reflect that it's now a place to note our broader thinking on the editor. Any particular tasks or editor-related bugs or enhancements should have their own issues.

**Comment by arthurattwell** [comment]
The editor is on the roadmap [here](https://trello.com/c/fZwUJALx/11-edit-in-an-editor).
