### ISSUE TITLE
Can't make submissions to private repos

### ISSUE THREAD

**Issue by SteveBarnett** [electricbookworks/electric-book-gui#32]
I can't "create an adaptation" of a private repo. This is important because CORE is a private repo.

I think this might be because my GitHub account, `SteveBarnett`, is a free one, so I can't have any private repos. @arthurattwell, if you run the EBM locally and fork a repo, does it work?

**Comment by SteveBarnett** [comment]
The log gives me (I entered my auth deets to see what happened):

```
I0322 14:51:16.559110   10964 Webserver.go:68] Listening on :16101
I0322 14:51:32.422846   10964 GitTools.go:110] Cloning/updating SteveBarnett/wits-university-press from https://github.com/electricbookworks/wits-university-press
Cloning into 'wits-university-press'...
Username for 'https://github.com': SteveBarnett
Password for 'https://SteveBarnett@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/electricbookworks/wits-university-press.git/'
```

and the browser 

```
exit status 128
```

**Comment by arthurattwell** [comment]
@SteveBarnett @craigmj This may be because of an organisation's Third Party Access policy on GitHub. Organisations can restrict third-party access in their settings. I found today that Electric Book Works has no restrictions, while Fire and Lion does restrict access. As a result, when I login in by authorising the EBM on GitHub, I can see EBW repos, but not F&L ones.

For an organisation that does have restrictions, users should be able to request access, which organisation admins can then choose to approve. To make this possible, it seems that the third-party app has to provide a list of organisations during OAuth. [This help article shows this](https://help.github.com/articles/requesting-organization-approval-for-third-party-applications/), and includes this screencap:

![image](https://cloud.githubusercontent.com/assets/1053331/24396598/06dcebae-13a4-11e7-9018-f03d5779d97f.png)

If during authorisation a user then clicks 'Request access' for an organisation with Third Party restrictions, then that org's admins can allow access, [as described here](https://help.github.com/articles/approving-third-party-applications-for-your-organization/).

So it looks like we need to add that step to our authorisation page/process. Right now, when I authorise the EBM there is no interstitial step for seeing which organisation's repos I'm giving the app access to.

Incidentally, I've temporarily removed Fire and Lion restrictions for today's demo, and will put them back afterwards.

**Comment by arthurattwell** [comment]
This seems to be working okay, so I'm closing. It may be working because we're currently asking for very broad permissions. So we might revisit this when we get the point of reducing the permissions we ask for.
