### ISSUE TITLE
Error when opening fork

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-gui#76]
I get this error when clicking Manage to open a fork:

![image](https://user-images.githubusercontent.com/1053331/27864148-a79b21dc-618d-11e7-876f-73a0145b7dc7.png)

This does not happen on all forks. So far just this particular repo.

**Comment by arthurattwell** [comment]
Ah, also getting it on all my repos.

![image](https://user-images.githubusercontent.com/1053331/27864210-eba47fd6-618d-11e7-98bc-76d38062a583.png)

I've tried revoking and redoing auth, but that doesn't help.

**Comment by craigmj** [comment]
Hi,
I'm not getting this myself, but I had everything crashing on demo with an 'out of disk space' issue... which I've fixed by deleting a whole lot of repos that I had, so we've got about 4G free on that now.
I think I need to add a 'disk free' meter to the UI, at least for us, so that if there's no disk space, we can catch it before it becomes an issue...
Please try again, and let's see if the issue was disk-space related.
Thanks,
C

**Comment by arthurattwell** [comment]
@craigmj No luck, I'm afraid. Still getting the error.
