### ISSUE TITLE
Deploy an EB GUI with a script

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book-gui#9]
As a technical user, I want a fast, easy way set up my own, self-hosted Electric Book GUI – for instance using Docker or Vagrant – so that I am never tied to one provider.

**Comment by arthurattwell** [comment]
@craigmj What is your basic process for deploying the latest version to the server at the moment? I'm thinking ahead to what our deployment process might be once we have tests in place.

**Comment by craigmj** [comment]
Deploying to the live server is a 3 step process:
1. I build it on my own machine - this is necessary because it will use the actual binary I build in the installation.
2. I push the sources to the appropriate remote (in this instance craigmj/master)
3. I run an ansible script that is in tools/ansible/.
In other words, I could reduce it to a single script that would do the full deployment.
BTW, that deployment would work as well to provision an entirely new machine. (In theory ;) In practice I'm pretty sure it would work...!)
Oh, the catch is the GitHub callbacks. I pass the GitHub client and secret to the ansible hosts file (see `hosts-test`). But the GitHub app needs to be configured with the fqdn or IP of your new server (or your localhost or your vm or whatever you're using). So to setup a new server, you need to configure the `hosts-newserver` file first, and for that you probably need to go to Github and configure an application.

**Comment by arthurattwell** [comment]
Thanks @craigmj. For now, I'd like to write that up in a wiki page, something like the list below. I've put a few questions in where I'm not sure what you mean (my learning curve). How does this look?

1. For the server, we use Ubuntu 16.04.2 x64 with 2 GB memory  and 40 GB disk space. YMMV.
1. Go to Github and configure a new application. Configure it with the fqdn or IP of your new server (or your localhost or vm). 
1. Configure the hosts-newserver file, using the GitHub client and secret for your app.
   *Do you mean what is currently `tools/ansible/hosts-test`? If so, presumably that file name will change one it's definitely working.*
1. Build the electricbook locally: `./build.sh`. The EBM server will use this binary.
1. Push the sources to the appropriate Git remote.
1. Run the ansible script that is in tools/ansible/.
   *`playbook-bookserver.yml`? And am I right that this is run on the server?*

**Comment by arthurattwell** [comment]
Now documented at https://electricbookworks.github.io/electric-book-gui/developers/
